import { Text, FlatList } from 'react-native';
import { FAB, Divider, Searchbar } from 'react-native-paper';

import { database } from '../../../data/_fakeDB';

import { PlaylistsCard } from '../../playlists/PlaylistsCard/PlaylistsCard';
import { PlaylistListItem } from '../../playlists/PlaylistListItem/PlaylistListItem';

import { Layout } from '../../commons/Layout/Layout';
import { SearchBar } from '../../commons/SearchBar/SearchBar';

import * as S from './styles';

export function PlaylistsPage() {
  return (
    <Layout>
      <SearchBar placeholder="Buscar por nome da playlist" />

      <FlatList
        data={database.autoGeneratedPlaylists}
        style={{ height: 120 }}
        contentContainerStyle={{ gap: 16 }}
        keyExtractor={(podcastChannel, index) => `${index}:${podcastChannel.title}`}
        renderItem={({ item: playlist }) => (
          <PlaylistsCard playlist={playlist} />
        )}
      />

      <S.Title style={{ fontSize: 14, marginTop: 16, marginBottom: 8 }}>
        Minhas Playlists
      </S.Title>

      <FlatList
        data={database.userGeneratedPlaylists}
        keyExtractor={(podcastChannel, index) => `${index}:${podcastChannel.title}`}
        renderItem={({ item: playlist, index }) => (
          <PlaylistListItem
            playlist={playlist}
            isFirstItem={index === database.userGeneratedPlaylists.length - 1}
          />
        )}
      />

      <FAB
        icon="plus"
        accessibilityLabel="Nova Playlist"
        onPress={() => console.log('Pressed')}
        style={{
          position: 'absolute',
          margin: 16,
          right: 0,
          bottom: 0,
        }}
      />
    </Layout>
  );
}
